server:
  port: 9002
spring:
  application:
    name: nacos-payment-provicer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
